import Link from "next/link";
import { TradePackCard } from "@/components/trade-pack-card";
import { tradePacks } from "@/data/trade-packs";

const faqs = [
  ["What is in a pack?", "Each pack contains the listed editable Word templates, an Excel administration workbook, a PDF read-me, PDF previews and a single-business licence."],
  ["Can I use the templates for my own business?", "Yes. Your one-off purchase allows one business to customise and use the files. You may not resell, share or distribute the templates."],
  ["Do I need a subscription?", "No. You pay once for the pack. After verified payment, DokKit sends access to the digital download."],
];

export default function Home() {
  return <>
    <section className="bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-6 sm:py-16 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:px-8 lg:py-24"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#a63d00]">Editable documents for South African trades</p><h1 className="mt-4 text-4xl font-black leading-[1.04] text-[#111111] sm:text-6xl">Quote it. Record it. Invoice it. Keep the work moving.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#4f4f55] sm:text-lg sm:leading-8">DokKit starter packs give electrical, plumbing, solar and electric-fence contractors practical customer paperwork and a simple admin workbook—ready to make your own.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/packages" className="inline-flex min-h-12 items-center justify-center rounded-md bg-[#c24100] px-6 py-3 text-sm font-black text-white shadow-lg transition hover:bg-[#9a3412]">Browse trade packs</Link><Link href="/free-business-admin-checklist" className="inline-flex min-h-12 items-center justify-center rounded-md border border-black/20 px-6 py-3 text-sm font-black text-[#111111] transition hover:border-[#c24100] hover:text-[#a63d00]">Get the free checklist</Link></div><p className="mt-5 text-sm font-bold text-[#5f5f66]">Pay once · Editable Word and Excel files · Secure PayFast checkout</p></div><div className="grid gap-3 rounded-xl bg-[#111111] p-5 text-white shadow-2xl sm:grid-cols-2 sm:p-7">{tradePacks.map((pack) => <Link key={pack.slug} href={`/packages#${pack.slug}`} className="rounded-lg border border-white/15 bg-white/5 p-4 transition hover:border-[#ffb06f] hover:bg-white/10"><p className="text-xs font-black uppercase tracking-[0.12em] text-[#ffb06f]">{pack.trade}</p><p className="mt-2 text-lg font-black">{pack.name}</p><p className="mt-3 text-sm text-white/70">{pack.documentCount} editable documents + Excel workbook</p></Link>)}</div></div></section>
    <section className="bg-[#fff4eb] py-12 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#a63d00]">Choose your trade</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Four focused packs. No filler library.</h2></div><div className="mt-8 grid gap-5 lg:grid-cols-2">{tradePacks.map((pack) => <TradePackCard key={pack.slug} pack={pack} />)}</div></div></section>
    <section className="bg-white py-12 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#a63d00]">Simple workflow</p><div className="mt-5 grid gap-5 md:grid-cols-3">{[["1", "Choose the right trade pack", "Review the exact documents and workbook included before adding it to your cart."], ["2", "Pay securely", "Complete your order with PayFast. There is no subscription or recurring charge."], ["3", "Edit and use the files", "After payment is verified, download your files and adapt them for your own business."]].map(([number, title, copy]) => <article key={number} className="rounded-xl border border-black/10 bg-[#f6f4f1] p-6"><p className="text-4xl font-black text-[#ff6a00]">{number}</p><h2 className="mt-4 text-xl font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-[#5f5f66]">{copy}</p></article>)}</div></div></section>
    <section id="faq" className="border-y border-black/10 bg-[#fff4eb] py-12 lg:py-20"><div className="mx-auto max-w-5xl px-5 sm:px-6 lg:px-8"><p className="text-center text-xs font-black uppercase tracking-[0.2em] text-[#a63d00]">FAQ</p><h2 className="mt-3 text-center text-3xl font-black sm:text-4xl">Before you buy</h2><div className="mt-8 grid gap-4">{faqs.map(([question, answer]) => <article key={question} className="rounded-xl bg-white p-5 shadow-sm"><h3 className="font-black">{question}</h3><p className="mt-2 text-sm leading-6 text-[#5f5f66]">{answer}</p></article>)}</div></div></section>
  </>;
}
