from __future__ import annotations

import argparse
import json
import os
import shutil
import tempfile
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


DEFAULT_PACK = Path(
    r"C:\Business\TEMPLATES.ZIP\NOT_READY\Generated_Industry_Packs_From_Cleaning_Blueprint_20260628_08\DokKit_Beauty_Salons_and_Spas_Complete_Pack_v1"
)


REPLACEMENTS: list[tuple[str, str]] = [
    ("BEAUTY SALONS AND SPAS", "HAIR, BEAUTY AND SPA"),
    ("Beauty Salons and Spas", "Hair, Beauty and Spa"),
    ("beauty and spa services", "hair, beauty and spa services"),
    ("Beauty and Spa Services", "Hair, Beauty and Spa Services"),
    ("Professional Beauty and Spa Services", "Professional Hair, Beauty and Spa Services"),
    ("Professional Beauty and Wellness Services", "Professional Hair, Beauty and Spa Services"),
    ("Commercial Corporate Service Proposal", "Salon, Bridal and Wellness Service Proposal"),
    ("Commercial Corporate Service Proposal", "Salon, Bridal and Wellness Service Proposal"),
    ("Commercial / Corporate Service Proposal", "Salon, Bridal and Wellness Service Proposal"),
    ("Commercial Corporate Service Proposal", "Salon, Bridal and Wellness Service Proposal"),
    ("Commercial / Corporate Service Proposal", "Salon, Bridal and Wellness Service Proposal"),
    ("Commercial Corporate Review Proposal", "Salon, Bridal and Wellness Service Proposal"),
    ("Commercial Corporate", "Salon, Bridal and Wellness"),
    ("Beauty Service Team", "Salon and Spa Team"),
    ("Beauty Team", "Salon and spa team"),
    ("beauty team", "salon and spa team"),
    ("beauty therapist", "therapist / stylist"),
    ("Beauty therapist", "Therapist / stylist"),
    ("Appointment beauty team", "Salon and spa teams"),
    ("office beauty companies", "salons, spas and mobile beauty businesses"),
    ("deep-beauty team", "advanced treatment teams"),
    ("mobile beauty operators", "mobile stylists and therapists"),
    ("small contract beauty businesses", "small hair, beauty and spa businesses"),
    ("beauty jobs", "appointments and treatment packages"),
    ("Beauty jobs", "Appointments and treatment packages"),
    ("client sites", "client records and appointment locations"),
    ("client site", "client appointment location"),
    ("Client site", "Client appointment location"),
    ("client sites, beauty jobs, recurring contracts, beauty supplies, staff work logs, site inspections, invoices and monthly beauty review records", "clients, appointments, treatment packages, retail products, staff rosters, consultation records, invoices and monthly business review records"),
    ("client sites, beauty jobs, recurring contracts, beauty supplies", "clients, appointments, treatment packages and retail products"),
    ("site inspections", "treatment-room checks"),
    ("site inspection", "treatment-room check"),
    ("Routine site inspections and quality assurance audits", "Routine treatment-room checks and client-service quality reviews"),
    ("Site inspections", "Treatment-room checks"),
    ("Site inspection", "Treatment-room check"),
    ("site inspections", "treatment-room checks"),
    ("site inspection", "treatment-room check"),
    ("commercial, industrial, and appointment clients", "salon, spa, bridal, event and personal-care clients"),
    ("commercial, industrial and appointment clients", "salon, spa, bridal, event and personal-care clients"),
    ("commercial, industrial", "salon, spa"),
    ("industrial", "professional-care"),
    ("operational demands", "appointment, hygiene, consultation and client-care demands"),
    ("operational meaning", "practical meaning"),
    ("Operational meaning", "Practical meaning"),
    ("operational notes", "appointment and service notes"),
    ("Operational notes", "Appointment and service notes"),
    ("operational use", "salon and spa use"),
    ("Operational use", "Salon and spa use"),
    ("operational support", "treatment support"),
    ("Operational support", "Treatment support"),
    ("Post-construction site clearing and dust removal", "Haircuts, blow-dries, colour services and styling"),
    ("Post-Construction / After-Builders Clean", "Colour Correction / Specialist Treatment"),
    ("After-Builders Clean", "Specialist Treatment"),
    ("Post-Construction", "Specialist Treatment"),
    ("post-construction", "specialist treatment"),
    ("move-in/out", "bridal / event"),
    ("move-in and move-out", "bridal and event"),
    ("Heavy dust, debris, paint marks, tiles, windows, and surfaces", "Consultation-led corrective colour, advanced facial, lash, brow, nail or spa treatment"),
    ("heavy dust, debris, paint marks, tiles, windows, and surfaces", "corrective colour, advanced facial, lash, brow, nail or spa treatment requirements"),
    ("heavy dust", "product build-up"),
    ("Heavy dust", "Product build-up"),
    ("debris", "product residue"),
    ("Debris", "Product residue"),
    ("paint marks", "colour banding"),
    ("Paint marks", "Colour banding"),
    ("tiles", "treatment areas"),
    ("Tiles", "Treatment areas"),
    ("exterior window beauty", "lash, brow, nail and skin-care add-ons"),
    ("High-specialist beauty add-on and exterior window beauty", "Advanced facials, peels, lash, brow and nail add-ons"),
    ("Deep beauty of ablution facilities", "Massage, body treatments and spa packages"),
    ("Safe, targeted, and compliant pest management solutions", "Retail aftercare, product recommendations and rebooking support"),
    ("pest management", "retail aftercare"),
    ("pest issues", "allergies or sensitivities"),
    ("pest concern", "allergy or sensitivity concern"),
    ("pest activity", "allergy or sensitivity concern"),
    ("Biohazard / pest / issue concern", "Client sensitivity / contraindication concern"),
    ("biohazard / pest / issue concern", "client sensitivity / contraindication concern"),
    ("PPE availability and use", "Salon hygiene and protective-item availability"),
    ("Personal Protective Equipment (PPE)", "salon hygiene and treatment safety standards"),
    ("PPE", "protective items"),
    ("SABS-approved, eco-friendly, and non-toxic beauty agents", "professional salon and spa products from reputable suppliers"),
    ("SABS-approved", "supplier-approved"),
    ("eco-friendly", "client-safe"),
    ("non-toxic beauty agents", "professional treatment products"),
    ("beauty agents", "treatment products"),
    ("Ablution", "Treatment room"),
    ("ablution", "treatment room"),
    ("Hazardous Product Agents Regulations", "Product Safety and Labelling Requirements"),
    ("hazardous product agents", "professional treatment products"),
    ("Hazardous product agents", "Professional treatment products"),
    ("hazardous waste", "regulated waste"),
    ("hazardous or restricted areas", "contraindicated, unsafe or restricted services"),
    ("The business may refuse to clean unsafe, unstable, hazardous or restricted areas.", "The business may refuse services where a contraindication, unsafe condition, missing consent or out-of-scope request creates risk."),
    ("Beauty may not fully remove old stains, issue, odours, issue, scale or marks caused by wear, age or neglect.", "Results may vary where hair, skin, nails or treatment areas have pre-existing damage, sensitivity, product build-up, prior colour, prior treatment history or medical considerations."),
    ("old stains, issue, odours, issue, scale or marks", "pre-existing damage, sensitivity, product build-up, prior colour or prior treatment effects"),
    ("excessive dirt, issue, issue, pet hair, hoarding conditions", "extra hair length or thickness, colour correction, product build-up, sensitivity, allergies or contraindications"),
    ("excessive dirt", "extra hair length or product build-up"),
    ("pet hair", "product build-up"),
    ("hoarding conditions", "complex treatment history"),
    ("hard-to-access areas", "mobile travel or after-hours appointments"),
    ("hard to access", "mobile or after-hours"),
    ("dirt", "product build-up"),
    ("Dirt", "Product build-up"),
    ("soil", "product residue"),
    ("Soil", "Product residue"),
    ("stains or soiling", "sensitivity or treatment-condition concerns"),
    ("Heavy stains or soiling", "Sensitivity or treatment-condition concern"),
    ("stains", "treatment concerns"),
    ("Stains", "Treatment concerns"),
    ("stain", "treatment concern"),
    ("Stain", "Treatment concern"),
    ("odour", "sensitivity"),
    ("Odour", "Sensitivity"),
    ("odours", "sensitivities"),
    ("Odours", "Sensitivities"),
    ("issue / odour / pest concern", "contraindication / allergy / sensitivity concern"),
    ("Issue / odour / pest concern", "Contraindication / allergy / sensitivity concern"),
    ("biohazard beauty", "medical or clinical procedure"),
    ("outdoor beauty", "venue setup outside the agreed appointment area"),
    ("carpet extraction", "specialist treatment not listed"),
    ("laundry, dishes, high windows, heavy furniture moving, issue treatment, biohazard beauty, outdoor beauty, carpet extraction or specialised services", "medical procedures, prescription advice, piercing, tattooing, hair extensions, chemical services not listed, venue hire, catering, transport or other services outside the agreed appointment scope"),
    ("General beauty of agreed rooms or areas.", "Agreed hair, beauty or spa treatments."),
    ("Service Area and preparation area beauty as agreed.", "Treatment-room preparation and client care as agreed."),
    ("Floor sweeping, mopping or vacuuming as applicable.", "Station setup, product preparation and tool sanitising as applicable."),
    ("Dusting and surface wipe-down within reachable areas.", "Client consultation, service notes and aftercare guidance."),
    ("Waste removal to designated bins where agreed.", "Safe disposal of single-use items where required."),
    ("General rooms / workspaces", "Treatment room / station"),
    ("Living / work areas", "Treatment area / client setup"),
    ("Living areas / Bedrooms", "Treatment areas / service items"),
    ("Bedroom / office", "Treatment room / station"),
    ("bedroom homes", "standard salon or spa appointments"),
    ("bedrooms", "treatment areas"),
    ("Bedrooms", "Treatment areas"),
    ("homes and apartments", "salon clients and mobile appointments"),
    ("Small homes and apartments", "Express appointments and first-time clients"),
    ("Homeowners / tenants", "Salon, spa and mobile clients"),
    ("Convenient clean home without extra time pressure.", "Polished personal care without appointment stress."),
    ("Book a reliable home clean for your schedule.", "Book a polished treatment experience that fits your schedule."),
    ("We handle the beauty so you can focus on your day.", "We handle the appointment details so you can enjoy the result."),
    ("homes, sites, venues, offices, shops, complexes or business premises", "salon rooms, spa venues, bridal parties, events or mobile appointments"),
    ("2-4 bedroom homes", "standard salon or spa appointments"),
    ("2– 4 bedroom homes", "standard salon or spa appointments"),
    ("2–4 bedroom homes", "standard salon or spa appointments"),
    ("Preparation Area, service areas, work areas, dusting, bins", "Consultation, treatment preparation, service delivery and aftercare notes"),
    ("Spring beauty or neglected areas", "Advanced or higher-effort treatment needs"),
    ("neglected areas", "advanced treatment needs"),
    ("Office Maintenance Plan", "Salon Membership / Retainer Plan"),
    ("Small to medium offices", "Regular clients, bridal parties or business wellness clients"),
    ("Carpet, windows, post-construction, other", "Bridal, colour, advanced skin, wellness or retail"),
    ("windows, post-construction", "colour, advanced treatment"),
    ("windows", "treatment areas"),
    ("Windows", "Treatment areas"),
    ("window", "treatment area"),
    ("Window", "Treatment area"),
    ("R20 - R45 per m2 or custom quote", "Quote after consultation"),
    ("R20 - R45 per m² or custom quote", "Quote after consultation"),
    ("R20 – R45 per m² or custom quote", "Quote after consultation"),
    ("R20 - R60 per window", "From R150 - R650"),
    ("R20 – R60 per window", "From R150 - R650"),
    ("Per square metre", "Per treatment / session"),
    ("per m2", "per treatment"),
    ("per m²", "per treatment"),
    ("Per m2", "Per treatment"),
    ("Per m²", "Per treatment"),
    ("m2", "treatment"),
    ("m²", "treatment"),
    ("Skin / Surface Care Service", "Skin, Hair or Nail Treatment"),
    ("Skin / Surface", "Skin / Hair / Nail"),
    ("Surface Care", "Treatment Care"),
    ("Surface", "Treatment"),
    ("surface", "treatment area"),
    ("Surfaces", "Treatment areas"),
    ("surfaces", "treatment areas"),
    ("Treatment Treatment", "Treatment"),
    ("Service Areas / toilets", "Treatment rooms / stations"),
    ("Service Areas", "Treatment Rooms / Stations"),
    ("service areas", "treatment rooms"),
    ("Service areas", "Treatment rooms"),
    ("Service Area", "Treatment Room"),
    ("service area", "treatment room"),
    ("Preparation Area / Break Area", "Treatment Setup / Product Preparation"),
    ("Preparation Area / break area", "Treatment setup / product preparation"),
    ("Preparation Area / food area", "Treatment setup / product preparation"),
    ("preparation area", "treatment setup"),
    ("Preparation Area", "Treatment Setup"),
    ("preparation areas", "treatment setup areas"),
    ("work areas", "treatment stations"),
    ("Work areas", "Treatment stations"),
    ("work area", "treatment station"),
    ("Work area", "Treatment station"),
    ("Client Treatment / Surface Type", "Hair / Skin / Nail / Treatment Type"),
    ("Client Treatment Type [Client / Site / Booking / Other]", "Service Type [Hair / Beauty / Spa / Bridal / Mobile / Other]"),
    ("Client / Site / Booking / Other", "Hair / Beauty / Spa / Bridal / Mobile / Other"),
    ("Number of Client Treatments / Areas", "Number of Clients / Services"),
    ("Primary service areas / items", "Treatment areas / service items"),
    ("Primary Service Areas / Items", "Treatment Areas / Service Items"),
    ("Visible finish / presentation", "Treatment finish / presentation"),
    ("Fixtures / equipment / records", "Tools / products / records"),
    ("Walls / paintwork", "Hair / skin / nail condition"),
    ("Cupboards / counters", "Treatment station / product area"),
    ("Appliances / fixtures", "Tools / equipment"),
    ("Furniture / decor", "Client chair / treatment bed"),
    ("Floor", "Station"),
    ("floor", "station"),
    ("Floors and carpets", "Treatment rooms and stations"),
    ("floors and carpets", "treatment rooms and stations"),
    ("Floors, carpets, and edges", "Treatment stations, tools and finish checks"),
    ("sweeping/vacuuming/mopping", "station setup and hygiene checks"),
    ("Sweeping/vacuuming/mopping", "Station setup and hygiene checks"),
    ("mopping", "station sanitising"),
    ("Mopping", "Station sanitising"),
    ("mopped", "sanitised"),
    ("Mopped", "Sanitised"),
    ("mop systems, buckets", "towels, tools and treatment equipment"),
    ("Mop system / buckets", "Towels / tools / treatment equipment"),
    ("mop, bucket, broom, vacuum", "combs, brushes, clips, towels"),
    ("mop, bucket, broom", "combs, brushes and clips"),
    ("mop systems", "salon tool systems"),
    ("Mop systems", "Salon tool systems"),
    ("mops, brushes, and buckets", "brushes, towels and tools"),
    ("mops", "tools"),
    ("Mops", "Tools"),
    ("mop", "tool"),
    ("Mop", "Tool"),
    ("bucket", "towel bin"),
    ("Bucket", "Towel bin"),
    ("broom", "brush"),
    ("Broom", "Brush"),
    ("vacuum", "salon tool"),
    ("Vacuum", "Salon tool"),
    ("duster", "brush"),
    ("Duster", "Brush"),
    ("scrub pads", "applicators"),
    ("Scrub pads", "Applicators"),
    ("scraper where safe", "applicator where appropriate"),
    ("wet-floor controls", "slip controls and treatment-room safety"),
    ("Wet-floor controls", "Slip controls and treatment-room safety"),
    ("Wet or slippery work areas", "Wet hair, spills or slippery treatment areas"),
    ("wet work areas", "wet treatment areas"),
    ("wet areas", "wet treatment areas"),
    ("toilet beauty therapist", "incompatible product"),
    ("toilet", "washroom"),
    ("Toilet", "Washroom"),
    ("toilets", "washrooms"),
    ("Toilets", "Washrooms"),
    ("restroom", "client washroom"),
    ("Restroom", "Client washroom"),
    ("bathroom", "washroom"),
    ("Bathroom", "Washroom"),
    ("kitchen", "back-of-house product area"),
    ("Kitchen", "Back-of-house product area"),
    ("dishes", "unrelated personal items"),
    ("Dishes", "Unrelated personal items"),
    ("bins", "disposal points"),
    ("Bins", "Disposal points"),
    ("bin", "disposal point"),
    ("Bin", "Disposal point"),
    ("waste", "single-use item"),
    ("Waste", "Single-use item"),
    ("dust", "product residue"),
    ("Dust", "Product residue"),
    ("dusting", "station preparation"),
    ("Dusting", "Station preparation"),
    ("clean home", "polished treatment"),
    ("Clean Home", "Polished Treatment"),
    ("home clean", "salon treatment"),
    ("Home Clean", "Salon Treatment"),
    ("Standard Home Clean", "Express Hair, Beauty or Spa Treatment"),
    ("Deep Clean", "Advanced Hair, Beauty or Spa Treatment"),
    ("deep clean", "advanced treatment"),
    ("Deep beauty", "Advanced treatment"),
    ("deep beauty", "advanced treatment"),
    ("Office Beauty", "Corporate / Event Beauty Service"),
    ("beauty of agreed rooms or areas", "hair, beauty or spa treatments"),
    ("beauty support", "treatment support"),
    ("beauty arrangement", "treatment package"),
    ("Beauty arrangement", "Treatment package"),
    ("beauty service description", "treatment description"),
    ("Beauty service description", "Treatment description"),
    ("Standard Edit description", "Edit treatment description"),
    ("completion notes", "service notes"),
    ("Completion notes", "Service notes"),
    ("client-ready project", "client-ready appointment"),
    ("Client-ready project", "Client-ready appointment"),
    ("project", "appointment"),
    ("Project", "Appointment"),
    ("job card", "appointment record"),
    ("Job card", "Appointment record"),
    ("job cards", "appointment records"),
    ("Job cards", "Appointment records"),
    ("jobs completed", "appointments completed"),
    ("Jobs completed", "Appointments completed"),
    ("completed jobs", "completed appointments"),
    ("Completed jobs", "Completed appointments"),
    ("job activity", "appointment activity"),
    ("Job activity", "Appointment activity"),
    ("job", "appointment"),
    ("Job", "Appointment"),
    ("snag", "service issue"),
    ("Snag", "Service issue"),
    ("handover notes", "aftercare notes"),
    ("Handover notes", "Aftercare notes"),
    ("handover", "aftercare"),
    ("Handover", "Aftercare"),
    ("service completion", "appointment completion"),
    ("Service Completion", "Appointment Completion"),
    ("Service scope", "Treatment scope"),
    ("service scope", "treatment scope"),
    ("service date", "appointment date"),
    ("Service Date", "Appointment Date"),
    ("service type", "treatment type"),
    ("Service type", "Treatment type"),
    ("Requested Service", "Requested Treatment"),
    ("Requested service", "Requested treatment"),
    ("service package", "treatment package"),
    ("Service Package", "Treatment Package"),
    ("Selected Treatment / Package [Service Package]", "Selected Treatment / Package [Treatment Package]"),
    ("Add-On Services", "Add-On Treatments / Retail Products"),
    ("add-on services", "add-on treatments / retail products"),
    ("Specialist Add-On Service", "Specialist Treatment Add-On"),
    ("Specialist Access Treatment", "Specialist Treatment Add-On"),
    ("Special Access Beauty Service", "Mobile / Special Setup Treatment"),
    ("Hospitality / Wellness Area Service", "Spa / Wellness Treatment Support"),
    ("Business Client Wellness Service", "Corporate Wellness / Group Booking"),
    ("Routine Treatment Service", "Routine Hair, Beauty or Spa Appointment"),
    ("Full-Day Therapist Support", "Full-Day Stylist / Therapist Support"),
    ("Once-Off Standard Treatment", "Once-Off Hair, Beauty or Spa Treatment"),
    ("Detailed Treatment Service", "Advanced Treatment Package"),
    ("Event / Bridal Preparation", "Event / Bridal Hair and Beauty Preparation"),
    ("Recurring Treatment Package", "Recurring Treatment / Membership Package"),
    ("Retail / Client-Facing Treatment", "Retail, Consultation and Aftercare Support"),
    ("Specialist Beauty Add-On", "Specialist Treatment Add-On"),
    ("Item-Based Beauty Service", "Retail Product or Add-On Treatment"),
    ("Large Treatment Package", "Bridal, Spa or Group Package"),
    ("R65 - R100 per hour", "From R250 - R650 per session"),
    ("R65 – R100 per hour", "From R250 - R650 per session"),
    ("R400 - R800 per day", "Quote per booking block"),
    ("R400 – R800 per day", "Quote per booking block"),
    ("R165 - R495 per hour", "Quote by therapist / stylist time"),
    ("R165 – R495 per hour", "Quote by therapist / stylist time"),
    ("per beauty therapist per hour", "per therapist / stylist session"),
    ("per hour", "per session"),
    ("per day", "per booking block"),
    ("per visit", "per appointment"),
    ("Per Visit", "Per Appointment"),
    ("Per visit", "Per appointment"),
    ("Monthly Admin Checklist", "Salon Monthly Admin Checklist"),
    ("Equipment Maintenance Log Template", "Salon Equipment and Tool Maintenance Log Template"),
    ("Equipment Register", "Salon Equipment and Tool Register"),
    ("Equipment Maintenance Log", "Salon Equipment and Tool Maintenance Log"),
    ("Equipment condition", "Salon equipment and tool condition"),
    ("Product & Chemical Use Log", "Product and Treatment Stock Use Log"),
    ("Product and Stock Use Log", "Product, Retail and Treatment Stock Log"),
    ("Product and Chemical Use Log", "Product and Treatment Stock Use Log"),
    ("Approved Supplier & Vendor List", "Approved Product Supplier and Service Provider List"),
    ("Supplier Contact List", "Product Supplier and Service Provider List"),
    ("spray bottles and labels", "product bottles, labels and applicators"),
    ("Spray bottles and labels", "Product bottles, labels and applicators"),
    ("Cloths, sponges and protective items", "Towels, capes, applicators and protective items"),
    ("Microfibre cloths, colour-coded cloths, sponges, applicators, brushes, tool, towel bin, brush, salon tool, applicator where appropriate, brush and extension tool.", "Combs, brushes, clips, capes, towels, tint bowls, applicators, nail tools, skin-care tools, massage supplies and sanitising materials."),
    ("Microfibre cloths, colour-coded cloths, sponges, applicators, brushes", "Combs, brushes, clips, capes, towels and applicators"),
    ("Deissuer, service area therapist / stylist, descaler, approved", "Shampoo, conditioner, colour, developer, wax, skin-care, nail products and approved"),
    ("Deissuer", "Product remover"),
    ("deissuer", "product remover"),
    ("descaler", "product remover"),
    ("Descaler", "Product remover"),
    ("sanitising of priority checkpoints", "sanitising of tools, treatment stations and client-contact items"),
    ("sanitising", "sanitising"),
    ("disinfectant", "sanitising product"),
    ("Disinfectant", "Sanitising product"),
    ("disinfection", "sanitising"),
    ("Disinfection", "Sanitising"),
    ("colour coding", "tool hygiene separation"),
    ("Colour coding", "Tool hygiene separation"),
    ("client feedback / appointment record / supervisor observation", "client feedback / appointment record / manager observation"),
    ("supervisor observation", "manager observation"),
    ("supervisor", "manager"),
    ("Supervisor", "Manager"),
    ("crew", "team"),
    ("Crew", "Team"),
    ("route", "appointment schedule"),
    ("Route", "Appointment schedule"),
    ("recurring visits", "recurring appointments"),
    ("Recurring visits", "Recurring appointments"),
    ("once-off jobs", "once-off appointments"),
    ("Once-off jobs", "Once-off appointments"),
    ("missed shifts", "missed appointments"),
    ("Missed shifts", "Missed appointments"),
    ("fuel, protective items, repairs, and subcontractors", "retail products, treatment stock, repairs and service providers"),
    ("products, supplies, fuel, protective items, repairs, and subcontractors", "retail products, treatment stock, towels, tools, repairs and service providers"),
    ("products, supplies, fuel", "retail products, treatment stock, towels"),
    ("subcontractors", "service providers"),
    ("Subcontractors", "Service providers"),
    ("SDS", "product safety instructions"),
    ("dilution", "product use"),
    ("Dilution", "Product use"),
    ("dwell time", "processing time"),
    ("Dwell Time", "Processing Time"),
    ("dwell time", "processing time"),
    ("wet", "damp"),
    ("Wet", "Damp"),
    ("no unauthorised chemical mixing", "no unauthorised product mixing"),
    ("chemical", "product"),
    ("Chemical", "Product"),
    ("chemicals", "products"),
    ("Chemicals", "Products"),
    ("site contacts", "appointment contacts"),
    ("site contacts", "appointment contacts"),
    ("household occupants", "client representatives"),
    ("household", "client"),
    ("Household", "Client"),
    ("work-area restrictions", "treatment restrictions"),
    ("damage reports", "treatment concern reports"),
    ("damage photos", "treatment concern photos"),
    ("before/after photos", "before-and-after treatment photos"),
    ("Before/after photos", "Before-and-after treatment photos"),
    ("proof-of-service", "appointment record"),
    ("Proof-of-service", "Appointment record"),
    ("service evidence", "appointment evidence"),
    ("Service evidence", "Appointment evidence"),
    ("safe access, parking and water/electricity", "safe access, parking, treatment space and product/equipment readiness"),
    ("water/electricity", "product/equipment readiness"),
    ("water, electricity", "treatment space and equipment access"),
    ("Water / Electricity", "Treatment Setup / Equipment"),
    ("Water / Power", "Treatment Setup / Equipment"),
    ("Quote after client consultation, treatment type and appointment duration", "Quote after consultation, service type, duration and product requirements"),
    ("client consultation, treatment type and appointment duration", "consultation, service type, duration and product requirements"),
    ("Daily, weekly, or customized office beauty schedules", "Daily, weekly or customised appointment and treatment schedules"),
    ("office beauty schedules", "appointment and treatment schedules"),
    ("office beauty", "salon, spa and mobile beauty"),
    ("Office beauty", "Salon, spa and mobile beauty"),
    ("Commercial / office beauty", "Corporate / group booking"),
    ("Commercial / Salon, spa and mobile beauty", "Corporate / group booking"),
    ("Carpet and upholstery detailed / advanced treatment", "Hair, skin, nail and body treatment packages"),
    ("Carpet and upholstery", "Hair, skin, nail and body"),
    ("after-builders", "advanced treatment"),
    ("After-builders", "Advanced treatment"),
    ("After-Builders", "Advanced treatment"),
    ("move-out appointments", "mobile or off-site appointments"),
    ("move-out", "mobile or off-site"),
    ("2– 4 bedroom homes", "standard salon or spa appointments"),
    ("2- 4 bedroom homes", "standard salon or spa appointments"),
    ("2 - 4 bedroom homes", "standard salon or spa appointments"),
    ("bedroom homes", "salon or spa appointments"),
    ("pest-contaminated areas", "client sensitivity or contraindication concerns"),
    ("pest-contaminated", "contraindicated"),
    ("pest contamination", "allergy or sensitivity risk"),
    ("pest infestations", "unsafe contamination or contraindications"),
    ("pest control", "medical or specialist services"),
    ("Pest control", "Medical or specialist services"),
    ("pets are present", "children or guests are present"),
    ("Pets are present", "Children or guests are present"),
    ("whether pets are secured", "whether children, guests or companions are safely clear of the treatment area"),
    ("Do not feed, handle, move or discipline pets", "Do not supervise, move or manage children, guests or companions"),
    ("Hazardous or biohazard condition is found", "Unsafe or contraindicated condition is found"),
    ("hazardous, medical, contraindicated or sharp single-use item", "medical, contaminated, contraindicated or sharp single-use item"),
    ("Do not handle hazardous, medical, contraindicated or sharp single-use item without escalation.", "Do not handle medical, contaminated, contraindicated or sharp single-use items without escalation."),
    ("hazardous product containers", "concentrated product containers"),
    ("Hazardous product containers", "Concentrated product containers"),
    ("hazardous, or concentrated products", "professional, concentrated or salon-use products"),
    ("commercial-grade, hazardous, or concentrated products", "professional salon-grade or concentrated products"),
    ("commercial-grade", "professional salon-grade"),
    ("Mproduct safety instructions", "product safety instructions"),
    ("treatment stations and client-contact items. Excluded unless separately quoted: medical or specialist services, issue remediation, regulated single-use item handling, medical or clinical procedure, high-access work, upholstery extraction, specialist treatment not listed", "tools, stations and client-contact items. Excluded unless separately quoted: medical or clinical procedures, prescription advice, piercing, tattooing, extensions, corrective services not listed or specialist treatments outside scope"),
    ("medical or specialist services, issue remediation, regulated single-use item handling, medical or clinical procedure, high-access work, upholstery extraction, specialist treatment not listed", "medical or clinical procedures, prescription advice, piercing, tattooing, extensions, corrective services not listed or specialist treatments outside scope"),
    ("homes, offices, rental units, treatment setups, treatment rooms, staff facilities, communal areas", "salon rooms, spa rooms, mobile appointments, bridal venues, treatment stations, staff areas and client waiting areas"),
    ("homes, offices, rental units", "salon rooms, spa rooms and mobile appointments"),
    ("Clean living, bedroom or office areas: treatment areas, desks, shelves, skirtings, doors, frames, reachable ledges and visible marks where safe.", "Complete final checks for treatment rooms, stations, tools, client areas, mirrors, retail displays and aftercare materials where applicable."),
    ("Treatment Room cleaned, descaled and hygienic.", "Treatment room prepared, sanitised and client-ready."),
    ("All quoted rooms and areas were cleaned according to scope", "All quoted treatments and service items were completed according to scope"),
    ("All quoted rooms and areas", "All quoted treatments and service items"),
    ("rooms and areas", "treatments and service items"),
    ("clean needles, bodily fluids, allergy or sensitivity risk", "handle sharps, bodily fluids, unsafe contamination or contraindications"),
    ("Do not clean needles", "Do not handle sharps"),
    ("clean around them carefully", "work around them carefully"),
    ("clean surrounding area", "sanitise the surrounding treatment area"),
    ("cleaned according", "completed according"),
    ("cleaned, single-use item handled", "sanitised, single-use items handled"),
    ("Cleaned / repaired / replaced", "Sanitised / repaired / replaced"),
    ("cleaned / repaired / replaced", "sanitised / repaired / replaced"),
    ("equipment cleaned", "equipment sanitised"),
    ("Cleaned", "Sanitised"),
    ("cleaned", "sanitised"),
    ("clean ", "prepare "),
    ("Clean ", "Prepare "),
    ("ChemClean", "SalonPro Supplies"),
    ("chemclean", "salonpro"),
    ("Heavy-duty product removers, station strippers, sanitizers", "Professional colour, wax, nail and skin-care products"),
    ("Green-certified bio-products", "Retail aftercare and professional spa products"),
    ("station strippers", "professional treatment removers"),
    ("strippers", "removers"),
    ("bedroom homes", "salon or spa appointments"),
    ("bedroom", "appointment"),
    ("bedrooms", "appointments"),
    ("homes", "clients"),
    ("deep-beauty", "advanced treatment"),
    ("deep beauty", "advanced treatment"),
    ("Visible treatment area beauty", "Visible treatment-area work"),
    ("treatment area beauty", "treatment-area work"),
    ("beauty beauty", "beauty work"),
    ("sensitivitys", "sensitivities"),
    ("pest signs", "contraindication signs"),
    ("Service area [Province / municipality / treatment rooms]", "Appointment area [Province / municipality / treatment rooms]"),
    ("Service area", "Appointment area"),
    ("Service Area", "Appointment Area"),
    ("Salon, spa and mobile beauty post", "Salon spotlight post"),
    ("Area-by-Area Room Audit Sheet", "Treatment Area Audit Sheet"),
    ("Area / room", "Treatment area / station"),
    ("Counters, sink, appliances, handles", "Treatment station, tools, products and client chair / bed"),
    ("Professional Hair, Hair, Hair, Beauty and Spa Services", "Professional Hair, Beauty and Spa Services"),
    ("Professional Hair, Hair, Beauty and Spa Services", "Professional Hair, Beauty and Spa Services"),
    ("Hair, Hair, Hair, Beauty and Spa", "Hair, Beauty and Spa"),
    ("Hair, Hair, Beauty and Spa", "Hair, Beauty and Spa"),
    ("hair, hair, hair, beauty and spa", "hair, beauty and spa"),
    ("hair, hair, beauty and spa", "hair, beauty and spa"),
    ("premier hair, hair, hair, beauty and spa services", "premier hair, beauty and spa services"),
    ("Core Beauty Services", "Core Hair, Beauty and Spa Services"),
    ("Beauty Packages", "Treatment Packages"),
    ("Retail and Aftercare", "Retail Products and Aftercare"),
    ("daily operations", "daily appointments"),
    ("daily appointmentss", "daily appointments"),
    ("Appointment salon and spa team", "Salon and spa team"),
    ("appointment salon and spa team", "salon and spa team"),
    ("subcontracted salon and spa team", "contracted stylists or therapists"),
    ("subcontracted", "contracted"),
    ("appointment beauty clients", "hair, beauty and spa clients"),
    ("clients, sites, records or deliverables", "clients, appointments, treatment rooms, records and service items"),
    ("sites, records or deliverables", "appointments, treatment rooms, records and service items"),
    ("regular home beauty", "routine salon, spa and mobile appointments"),
    ("short-term or once-off treatment services", "once-off, bridal, mobile or event treatment services"),
    ("high-use, neglected, move-in, mobile or off-site and once-off appointments and treatment packages", "high-detail, corrective, bridal, mobile, off-site and once-off appointments and treatment packages"),
    ("neglected, move-in", "corrective, bridal"),
    ("move-in, mobile", "bridal, mobile"),
    ("every advanced treatment and spa service", "every advanced hair, beauty or spa service"),
    ("detailed / advanced treatment work", "advanced treatment work"),
    ("high-product residue areas", "high-detail treatment areas"),
    ("heavy product residue", "complex product build-up"),
    ("pre-existing marks", "pre-existing treatment concerns"),
    ("areas likely to require extra time", "services likely to require extra time"),
    ("Quality check A structured inspection", "Quality check A structured review"),
    ("structured inspection", "structured review"),
    ("Inspection", "Review"),
    ("inspection", "review"),
    ("South African beauty businesses", "South African hair, beauty and spa businesses"),
    ("Standard once-off beauty service where no detailed or specialist scope is required.", "Standard once-off treatment with consultation, preparation, service delivery and aftercare guidance."),
    ("Aftercare, event, appointment or booking support before or after an agreed milestone.", "Bridal, event or special-occasion preparation with timing, trial notes and client preferences."),
    ("for clients, appointments, treatment rooms, records and service items and hair, beauty and spa clients.", "for hair, beauty and spa clients."),
    ("each treatment services appointment", "each appointment"),
    ("This SOP applies to routine salon, spa and mobile appointments, once-off treatment services, setup, close-out and aftercare preparation where detailed / advanced treatment is not separately scoped, short-term rental beauty, recurring appointment hair, beauty and spa services and selected add-on beauty tasks agreed with the client.", "This SOP applies to routine salon, spa and mobile appointments, once-off treatments, bridal or event bookings, recurring packages and selected add-on services agreed with the client."),
    ("Included areas normally cover scope items, priority areas, aftercare points, treatment rooms, treatment setups, treatment stations, visible treatment areas, accessible fixtures and agreed priority checkpoints.", "Included scope normally covers client consultation, treatment preparation, service delivery, aftercare notes, treatment-room readiness, products, tools and agreed priority checks."),
    ("Excluded areas must be confirmed before work starts.", "Excluded services must be confirmed before work starts."),
    ("Exclusions may include regulated single-use item, client sensitivity or contraindication concerns, bodily fluids, issue removal beyond treatment area wiping, biohazards, roof spaces, blocked drains, specialist specialist treatment not listed, exterior treatment areas, high ladder work, heavy lifting and tasks outside the quoted scope", "Exclusions may include medical advice or procedures, prescription products, piercing, tattooing, unlisted chemical services, contraindicated work, unsafe conditions, venue services, transport and anything outside the quoted treatment scope"),
    ("specialist specialist treatment", "specialist treatment"),
    ("short-term rental beauty", "bridal or event bookings"),
    ("selected add-on beauty tasks", "selected add-on services"),
    ("area-by-area beauty", "treatment-area delivery"),
    ("detailed product residue removal, concern removal, treatment room descaling, treatment setup beauty, appliance exterior beauty, reachable fixtures, cupboards, skirtings, doors, handles, internal treatment areas, treatment stations and final sanitising of tools, treatment stations and client-contact items.", "advanced preparation, corrective treatment steps, product build-up management, treatment-room readiness, tool checks, station setup, mirrors, client areas and final sanitising of tools, stations and client-contact items."),
    ("product residue removal, concern removal, treatment room descaling, treatment setup beauty, appliance exterior beauty, reachable fixtures, cupboards, skirtings, doors, handles, internal treatment areas, treatment stations", "advanced preparation, corrective treatment steps, product build-up management, treatment-room readiness, tool checks, station setup, mirrors and client areas"),
    ("concern removal beyond treatment area wiping", "concern resolution beyond the agreed treatment scope"),
    ("issue removal", "concern resolution"),
    ("treatment setup beauty", "treatment setup"),
    ("appliance exterior beauty", "equipment readiness"),
    ("Client / site [Client name / site address]", "Client / appointment [Client name / appointment location]"),
    ("Treatment type [Appointment / commercial / advanced treatment / bridal / event / mobile appointment schedule]", "Treatment type [Hair / beauty / spa / bridal / event / mobile appointment]"),
    ("client client treatment care", "client care"),
    ("product product safety instructionss", "product safety instructions"),
    ("site risk assessment", "appointment risk notes"),
    ("scope of work", "treatment scope"),
    ("Areas inspected", "Treatment areas reviewed"),
    ("areas inspected", "treatment areas reviewed"),
    ("client client treatment", "client belongings and treatment area"),
    ("Client client treatment", "Client belongings and treatment area"),
    ("Client Client Treatment", "Client Belongings and Treatment Area"),
]


def apply_replacements(text: str) -> tuple[str, int]:
    count = 0
    for old, new in REPLACEMENTS:
        occurrences = text.count(old)
        if occurrences:
            text = text.replace(old, new)
            count += occurrences
    return text, count


def patch_zip_file(path: Path) -> int:
    total = 0
    with ZipFile(path, "r") as zin:
        entries = [(info, zin.read(info.filename)) for info in zin.infolist()]
    fd, temp_name = tempfile.mkstemp(suffix=path.suffix)
    os.close(fd)
    Path(temp_name).unlink(missing_ok=True)
    try:
        with ZipFile(temp_name, "w", ZIP_DEFLATED) as zout:
            for info, data in entries:
                if info.filename.endswith((".xml", ".rels")):
                    try:
                        text = data.decode("utf-8")
                    except UnicodeDecodeError:
                        zout.writestr(info, data)
                        continue
                    text, count = apply_replacements(text)
                    total += count
                    data = text.encode("utf-8")
                zout.writestr(info, data)
        shutil.move(temp_name, path)
    finally:
        Path(temp_name).unlink(missing_ok=True)
    return total


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pack", type=Path, default=DEFAULT_PACK)
    args = parser.parse_args()

    if not args.pack.exists():
        raise SystemExit(f"Pack folder not found: {args.pack}")

    results: dict[str, int] = {}
    for path in sorted(args.pack.iterdir()):
        if path.suffix.lower() in {".docx", ".xlsx"}:
            count = patch_zip_file(path)
            if count:
                results[path.name] = count

    print(json.dumps({"pack": str(args.pack), "files_changed": len(results), "replacement_hits": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
